# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 602914ce350ac3e8d2b87cd9a6e187104d239e9507f6fa14831b842f9d871e9e7e18ae79ccf4408281db3e05b630c56e3961e3ad00db5c088129e42518d9150b

test:
  secret_key_base: e367a715376424c8e8dcfaa4260d8955a42c8d51864bef174205ee7520c746add4d7d65f327bf1445ead5b5ff8646fda48a0d28b48c56979de44f73909984896

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
